### ISSUE TITLE
Man need help!

### ISSUE THREAD

**Issue by borodadada** [johnnywang1994/vue3-ssr#2]
Hello. I try build and =>

```
> vue-ssr@1.0.0 build:server D:\js\vue3-ssr-master
> cross-env NODE_ENV=production webpack --config config/server.config.js

[webpack-cli] Error: For the selected environment is no default ESM chunk format available:
ESM exports can be chosen when 'import()' is available.
JSONP Array push can be chosen when 'document' is available.
Select an appropriate 'target' to allow selecting one by default, or specify the 'output.chunkFormat' directly.
    at D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\config\defaults.js:679:11
    at F (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\config\defaults.js:71:15)
    at applyOutputDefaults (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\config\defaults.js:671:2)
    at applyWebpackOptionsDefaults (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\config\defaults.js:182:2)
    at createCompiler (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\webpack.js:78:2)
    at create (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\webpack.js:127:16)
    at webpack (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\webpack.js:135:47)
    at WebpackCLI.f [as webpack] (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack@5.52.0_webpack-cli@4.8.0\node_modules\webpack\lib\index.js:55:16)
    at WebpackCLI.createCompiler (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack-cli@4.8.0_82e74beaa24f9df23a29ca2ca1fc056f\node_modules\webpack-cli\lib\webpack-cli.js:2093:29)
    at async WebpackCLI.runWebpack (D:\js\vue3-ssr-master\node_modules\.pnpm\webpack-cli@4.8.0_82e74beaa24f9df23a29ca2ca1fc056f\node_modules\webpack-cli\lib\webpack-cli.js:2213:20)
 ERROR  Command failed with exit code 2.
 ERROR  Command failed with exit code 1.
```

WTF?

**Comment by caltonzhou** [comment]
I created a pull request to fix this issue. Enjoy vue.

[pull request](https://github.com/johnnywang1994/vue3-ssr/pull/3)
